config/routes.rb
Rails.application.routes.draw do
#nesting the payments under orders because there wont be payments without an order
  devise_for :users
  root to: 'pages#home'
  resources :restaurants do
    resources :deals
    resources :bookings, only: [:new, :create, :show] do
      resources :payments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  belongs_to :deal

  monetize :price_cents
end

app/models/business_hour.rb
class BusinessHour < ApplicationRecord
  belongs_to :restaurant
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :restaurant
  has_many :bookings
  has_many :users, through: :bookings
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  monetize :price_cents
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :deals
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :location, presence: true
  validates :user, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # validates :cuisine, inclusion: ["amerikanisch", "französisch", "asiatisch", "burger", "dessert", "deutsche küche", "fisch", "gesund", "exklusive deals", "indisch", "italienisch", "japanisch", "koreanisch", "mediterranean", "mexikanisch", "pizza", "sandwiches", "sushi", "syrisch", "thailändisch", "türkisch", "vegetarisch", "vietnamesisch", "other"]

  # validates :cuisine, inclusion: ["modern european", "salad", "gastropub", "asian", "japanese", "italian", "french", "vietnamese", "eastern european", "burrito"]

  mount_uploader :photo, PhotoUploader

  def self.cuisine_types
    pluck(:cuisine).uniq
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :deal
  has_many :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :restaurants, dependent: :destroy
  has_many :deals, through: :bookings
  has_many :bookings
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def default_url_options
   { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create, :show]
  before_action :find_booking, only: [:show]
  before_action :find_deal, only: [:create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.booking_time = Time.zone.parse(booking_params[:booking_time])
    @booking.user = current_user
    @booking.restaurant = @restaurant
    @booking.payment_state = 'pending'
    @booking.price_cents = (@deal.price_cents * booking_params[:amount].to_i)
    if @booking.save
      redirect_to restaurant_booking_path(@restaurant, @booking)
    else
      render 'new'
    end
  end

  def show

  end

  def booking_params
    params.require(:booking).permit(:booking_type, :booking_time, :user_id, :deal_id, :restaurant_id, :amount, :price_cents)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def find_deal
    @deal = Deal.find(booking_params[:deal_id])
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @deals = Deal.all
  end

  def show
    @deal = Deal.find(params[:id])
    @deals = Deal.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  #because there has to be an order before payment
  before_action :set_booking
  before_action :find_restaurant

  def new
    #display the Stripe button
  end

  def create
  customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @booking.price_cents,
    currency:     @booking.price.currency
  )

  @booking.update(payment: charge.to_json, payment_state: 'paid')
  redirect_to restaurant_booking_path(@restaurant, @booking)

rescue Stripe::CardError => e
  flash[:alert] = e.message
  redirect_to  restaurants_path
end

private

  def set_booking
    @booking = current_user.bookings.where(payment_state: 'pending').find(params[:booking_id])
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @restaurant = Restaurant.all
    @restaurant = @restaurant.where(cuisine: params[:cuisine_types]) if params[:cuisine_types].present?
    @restaurant = @restaurant.where("price_category <= ?", params[:price_category]) if params[:price_category].present?
    @restaurant = @restaurant.where("rating >= ?", params[:rating]) if params[:rating].present?
    @restaurants_geo = @restaurant.near(params[:location], 3) if params[:location].present?
    @restaurants_geo = @restaurant.near(params[:location_form], 3) if params[:location_form].present?
    @restaurants_geo = @restaurant if @restaurants_geo.nil?
    @markers = @restaurants_geo.map do |restaurant|
      {
        lng: restaurant.longitude,
        lat: restaurant.latitude,
        infoWindow: { content: render_to_string(partial: "/restaurants/map_window", locals: { restaurant: restaurant }) },
        id: restaurant.id
      }
    end
  end

  def show
    @restaurant = Restaurant.where(id: params[:id])
    @deals = Deal.where(restaurant_id: params[:id])
    @markers = @restaurant.map do |restaurant|
      {
        lng: restaurant.longitude,
        lat: restaurant.latitude,
        infoWindow: { content: render_to_string(partial: "/restaurants/map_window", locals: { restaurant: restaurant }) },
        id: ''
      }
    end
    @restaurant = Restaurant.find(params[:id])
    @restaurant_opening_hours = BusinessHour.where(restaurant_id: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurants_path
    else
      render new_restaurant_path
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :cuisine, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container form-wrapper">
  <div class="booking-page">
   <center> <h1>Please select your booking date and your deal </h1> </center>

   <%= simple_form_for [@restaurant, @deals, @booking] do |b| %>

   <div class="flex-container-booking-all">
    <div class="flex-container-booking">

    <div class="booking-time">
      <%= b.input :booking_time, as: :string, required: false, input_html: {class: "datepicker form-inline"} %>
    </div>
      <div>
        <%= b.association :deal, collection: @restaurant.deals, value: "1" %>
      </div>
      <div>
        <%= b.input :amount, collection: 1..5, input_html: {class: "amount-of-deals", id: "amount"} %>
      </div style="width: 21.5vw; margin: 0 auto;">
      <div class="price-of-deal">
        <p> Price </p>
        <!-- <div class="display-price"> -->
          <select class="display-price" id="priceselect" style="pointer-events: none;">
            <option value="" style="color: lightgrey !important">select a deal please</option>
            <%= @restaurant.deals.each do |deal|  %>
            <option value="<%= deal.name %>"><%= deal.price %>€</option>
            <% end %>
          </select>
          <!--    </div> -->
        </div>
        <div class="total-sum">
          <p> Total:  </p>
          <p id="total-price">  € </p>
        </div>
      </div>
        <%= b.submit "Confirm Booking" , class: "booking-button booking-button-margin" %>

    </div>
  </div>

</div>

<% end %>



<%= javascript_pack_tag 'form' %>

app/views/bookings/show.html.erb
<div class="container form-wrapper">
  <div class="booking-page">

    <% if @booking.payment_state == 'pending' %>
 <center> <h1>Please check your booking </h1> </center>
  <div class="flex-container-booking-all">
    <h2><strong>Your selected Restaurant:</strong></h2>

    <p><%= @restaurant.name %></p>
   <div class="restaurant-picture">
        <% if @restaurant.photos %>
        <img class= "picture-restaurant" src="<%= @restaurant.photos.first %>">
        <% end %>
      </div>
    <h2><strong>Your Order:</strong></h2>
    <p><%= @booking.amount %> x <%= @booking.deal.name %></p>
    <h2><strong>Date:</strong></h2>
    <p><%= @booking.booking_time.strftime('%e. %B %Y %m:%M') %></p>
    <hr/>

    <%= form_tag restaurant_booking_payments_path(@restaurant, @booking) do %>
    <article>
      <label class="amount">
        <span>Amount: <%= humanized_money_with_symbol(@booking.price) %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Booking"
    data-email="<%= current_user.email %>"
    data-amount="<%= @booking.price_cents %>"
    data-currency="<%= @booking.price.currency %>"></script>

    <% end %>

    <% else %>
    <div class="success-message">
     <center> <i class="fas fa-check-circle"></i>
     <h1>Thanks for your booking </h1>
    <h2>See you <%= @booking.booking_time.strftime('%e. %B %Y %m:%M') %>!</h2></center>
</div>
    <% end %>
</div>
  </div>
</div>

app/views/deals/create.html.erb
<h1>Deals#create</h1>
<p>Find me in app/views/deals/create.html.erb</p>

app/views/deals/destroy.html.erb
<h1>Deals#destroy</h1>
<p>Find me in app/views/deals/destroy.html.erb</p>

app/views/deals/edit.html.erb
<h1>Deals#edit</h1>
<p>Find me in app/views/deals/edit.html.erb</p>

app/views/deals/index.html.erb
<h1>Deals#index</h1>
<p>Find me in app/views/deals/index.html.erb</p>

app/views/deals/show.html.erb
<h1>Deals#show</h1>
<p>Find me in app/views/deals/show.html.erb</p>

app/views/deals/update.html.erb
<h1>Deals#update</h1>
<p>Find me in app/views/deals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- <title> Dailycato - Find the best lunch deals nearby </title> -->
  <title><%= meta_title %></title>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= meta_title %>">
  <meta name="twitter:description" content="<%= meta_description %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= meta_image %>">

  <%#= csrf_meta_tags %>
  <%#= action_cable_meta_tag %>
  <%= stylesheet_pack_tag "map" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %>

  <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Andika" rel="stylesheet"> -->
    <link rel="icon" type="image/ico" href="app/assets/images/dailycato_logo.ico">
    <%= favicon_link_tag 'favicon-32x32.png' %>

  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render "components/navbar" %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
    <%= render "components/footer" %>

  </body>
  </html>

app/views/pages/product_summary.html.erb
<h1>This is a test</h1>

app/views/payments/new.html.erb
<h1>Purchase of teddy <%= @order.teddy_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Teddy"
    data-email="<%= current_user.email %>"
    data-description="Teddy <%= @order.teddy_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>

app/views/restaurants/_filter.html.erb
 <div class="filter-title">
  <p>Cuisines</p>
</div>
<div class="cuisine-selection">
  <%= form_tag restaurants_path, :method => :get do %>
  <input type="hidden" class="input-form-index hidden-location-input" value="" name="location_form" id="restaurant_location" placeholder="e.g. Berlin">
  <% Restaurant.cuisine_types.each do |cuisine| %>
<div class="cuisine-btn">
  <%= check_box_tag "cuisine_types[]", cuisine, nil, id: "cuisine_#{cuisine.parameterize}" %>



  <label class="checkcontainer">
    <input type="checkbox">
    <span class="checkmark hover-option"></span>
  </label>
  <%= label_tag "cuisine_#{cuisine.parameterize}", cuisine %>
  </div>
  <% end %>
</div>


<div class="filter-title">
  <p>Rating</p>
</div>

<div class="star-ratings">
  <% (1..5).to_a.each do |num| %>
  <div id="star_<%= num %>" class="star-btn">
    <label  class="fa fa-star fa-fw" for="rating_<%= num %>"></label>
    <input class="star_input" type="checkbox" name="rating" id="rating_<%= num %>" value="<%= num %>">
  </div>
  <% end %>
</div>


<div class="filter-title">
  <p>Budgets</p>
</div>
<div class="cost-ratings">
  <% (1..4).to_a.each do |num| %>
  <!-- <div class="category-price"> -->
    <div id="btn_<%= num %>" class="money-btn">
      <%= label_tag("price_category_#{num}", "€" * num) %>
    </div>
    <%= radio_button_tag(:price_category, num) %>
    <!-- </div> -->
    <% end %>
  </div>
  <div class="filter-submit-btn">
  <%= submit_tag 'Filter' %>
</div>
  <% end %>

<script>
  fakeinputs = document.querySelectorAll(".checkcontainer")

  fakeinputs.forEach(function(fakeinput){

    fakeinput.addEventListener("click", function(){
      check = fakeinput.previousElementSibling

        check.checked = true


    })
  })



</script>

app/views/restaurants/_map_window.html.erb
<div>
  <div class="restaurant-logo">
    <% if restaurant.photos %>
    <img src="<%= restaurant.photos.first %>" alt="">
    <% end %>
  </div>
  <h1><%= restaurant.name %></h1>
  <% if restaurant.rating %>
  <p><% restaurant.rating.floor.times do %>
    <i class="fa fa-star checked"></i>
    <% end %>
    <% if restaurant.rating.round.even? %>
    <i class="fas fa-star-half-alt"></i>
    <% end %>
    <% (5 - restaurant.rating.floor).times do %>
    <span class="fa fa-star"></span>
    <% end %>
    <% end %>

  </p>
  <p><%= restaurant.location %></p>

  <div class="details-button">
    <p><%= link_to "See Deals", restaurant_path(restaurant)%></p>
  </div>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :cuisine, :collection => ["modern european", "salad", "gastropub", "asian", "japanese", "italian", "vietnamese", "eastern european", "burrito"] %>
<%= f.input :location %>
<%= f.submit %>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="index_flex">
  <div class="offers-container">

    <div class ="helper-bar">
      <form class="form-inline offer-location-search" action="<%= restaurants_path %>">
        <div class="form-group index-search" >
         <input type="text" class="input-form-index" value="<%= params[:location] %>" name="location" id="restaurant_location" placeholder="e.g. Berlin">

         <button type="submit"  class="search-index-btn">
          <i class="fa fa-arrow-circle-right fa-lg"></i>
        </button>
        <div class="filteropen" id="filter-button"><i class="fas fa-filter icon" style></i>Filter</div>
      </div>

    </form>
    <div class="filtercontainer">
      <%= render "filter" %>
    </div>
  </div>

  <div class="headline-search">
    <h1>We have found <%= pluralize(@restaurant.count, 'deal', 'deals') %> around, for <span id="date"></span>:</h1>
  </div>
  <% @restaurant.each do |restaurant| %>
  <div class="offer-detail" onclick="location.href='<%= restaurant_path(restaurant, location: params[:location], location_form: params[:location_form])%>';">

   <div class="left-box" style="background-image: linear-gradient(385deg, rgba(14, 14, 14, 0.39) 35%, rgba(240, 240, 240, 0) 104%), url(<%= image_path(restaurant.photos.first) %>);">

    <div class="offer-count marker-pin">
      <p><%= restaurant.id %></p>
    </div>
    <div class="restaurant-details">

      <h3><%= restaurant.name %></h3>
      <% if params[:location] %>
        <% if restaurant.distance_to(params[:location],:km) %>
        <p><%= restaurant.distance_to(params[:location],:km).round(2) %> km</p>
        <% end %>
      <% end %>


      <% if params[:location_form] %>
        <% if restaurant.distance_to(params[:location_form],:km) %>
        <p><%= restaurant.distance_to(params[:location_form],:km).round(2) %> km</p>
        <% end %>
      <% end %>

      <% if restaurant.rating %>
      <p><% restaurant.rating.floor.times do %>
        <i class="fa fa-star checked"></i>
        <% end %>
        <% if restaurant.rating.round.even? %>
        <i class="fas fa-star-half-alt"></i>
        <% end %>
        <% (5 - restaurant.rating.floor).times do %>
        <span class="fa fa-star"></span>
        <% end %>
        <% end %>
      </p>

      <p><%= restaurant.location %></p>
      <!--  <p><%= restaurant.rating %></p> -->
      <p><%= restaurant.cuisine.titleize %></p>
    </div>
  </div>



  <div class="restaurant-offer">

    <div class="deals-header">
      <div class="new-flex">
        <p> Friday's Special Deals:</p>
        <img src="https://i.imgur.com/c5eOGpA.png" alt="" height="35" width="35">
      </div>
    </div>
    <p><% restaurant.deals[0..2].each do |d|  %></p>
    <div class="offer-name">
      <div class="flex-text">
        <p><strong><%= d.name %></strong></p>
        <p><%= truncate(d.description, length: 45) %></p>
      </div>
      <div class="offer-price">
        <p><%= humanized_money_with_symbol(d.price) %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>
</div>
<div

id="map"
class="map-index"

data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAP_API'] %>"
></div>
</div>
</div>

<div class="dropdown-menu">
  <h6 class="dropdown-header">Dropdown header</h6>
  <a class="dropdown-item" href="#">Action</a>
  <a class="dropdown-item" href="#">Another action</a>
</div>

<script>
  a = document.querySelector('.filteropen')
  b = document.querySelector('.filtercontainer')
  a.addEventListener('click', function(){
    b.classList.toggle('filterisopen')
    document.querySelector(".cuisine-selection").classList.toggle("filter_open_cuisine")
    document.querySelector(".cost-ratings").classList.toggle("filter_open")
    document.querySelector(".star-ratings").classList.toggle("filter_open")
  })


  document.querySelectorAll("form")[1].addEventListener("submit" , function(){
    event.preventDefault();
    locatio = document.querySelector("#restaurant_location").value
    document.querySelector(".hidden-location-input").setAttribute("value", locatio)
    document.querySelectorAll("form")[1].submit()
  })

</script>

<%= javascript_pack_tag 'textShorten' %>

app/views/restaurants/new.html.erb
<h1>Add restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :cuisine, :collection => ["modern european", "salad", "gastropub", "asian", "japanese", "italian", "vietnamese", "eastern european", "burrito"] %>
<%= f.input :location %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="flex-box">
  <div class="flex-left">
    <div class="outter-box">
        <% if @restaurant.photos %>
      <div class="restaurant-picture" style="background-image: url('<%=image_path @restaurant.photos.first %>');">
        <!-- <img class= "picture-restaurant"  -->
        <% end %>
      </div>
      <div class="details-restaurant">
        <h1><%= @restaurant.name %></h1>
      <% if params[:location] %>
        <% if @restaurant.distance_to(params[:location],:km) %>
        <p><%= @restaurant.distance_to(params[:location],:km).round(2) %> km</p>
        <% end %>
      <% end %>


      <% if params[:location_form] %>
        <% if @restaurant.distance_to(params[:location_form],:km) %>
        <p><%= @restaurant.distance_to(params[:location_form],:km).round(2) %> km</p>
        <% end %>
      <% end %>
        <p><%= @restaurant.location %></p>

        <% if @restaurant.rating %>
      <p><% @restaurant.rating.floor.times do %>
        <i class="fa fa-star checked"></i>
        <% end %>
        <% if @restaurant.rating.round.even? %>
        <i class="fas fa-star-half-alt"></i>
        <% end %>
        <% (5 - @restaurant.rating.floor).times do %>
        <span class="fa fa-star"></span>
        <% end %>
        <% end %>
      </p>
      </div>

      <%# if true %>
     <!--  <div class="category-tag">
        <p>Modern-Asian</p>
      </div>
      <%# end %>
      <%# if false %>
      <div class="category-tag">
        <p>another category</p>
      </div>
      <%# end %>
      <%# if false %>
      <div class="category-tag">
        <p>category</p>
      </div> -->
      <%# end %>

      <div class="contact-display">
        <a href="tel: <%= @restaurant.phone_number %>" target="_blank"> <i class="fas fa-phone-square" style="font-size:30px;"></i></a>
      </div>
    </div>

    <div class="all-deals">
      <h2>Deals:</h2>
     <div class="details-deals">
      <div class="end-marker">
        <p><% @restaurant.deals.each  do |d|  %></p>
        <div class="deal-title">
          <p><strong><%= d.name %></strong></p>
        </div>
        <div class="deal-description-price">
          <p><%= d.description %></p>
          <div class="deal-price"> <!-- <p><%= d.price %>€</p></div> -->
          <p><%= humanized_money_with_symbol(d.price) %></p></div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <br>


  <div class="booking-section">
    <%= link_to "Book Now", new_restaurant_booking_path(@restaurant), class: "booking-button" %>
  </div>
</div>

<div class="flex-right">
  <div class="flex-container-all-boxes">
    <div class="flex-container map">
      <div class="map-wrapper">

        <div
        id="map"
        style="width: 100%;
        height: 100%;"

        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAP_API'] %>"
        ></div>
      </div>
    </div>

    <div class="flex-container">
      <h2 class="box-title">Opening Hours</h2>
      <table class="opening-table">
        <% counter =  1 %>
        <% @restaurant_opening_hours.each do |daily|%>

        <tr class="<%= 'today' if Date.today.wday == counter %>"><th><%= daily.day.capitalize! %></th><td><%= daily.closed_time %> - <%= daily.open_time %></td></tr>
        <% counter += 1 %>
        <% end %>
      </table>
    </div>


    <div class="flex-container-reviews">
      <h2 class="box-title">Reviews</h2>
      <% @restaurant.reviews.each do |review|  %>
      <div>
        <%= review.name %> - <% review.rating.floor.times do %>
        <i class="fa fa-star checked"></i>
        <% end %>
        <% if review.rating.round.even? %>
        <i class="fas fa-star-half-alt"></i>
        <% end %>
        <% (5 - review.rating.floor).times do %>
        <span class="fa fa-star"></span>
        <% end %>
      </div>
      <div class="review-text">
        <%= review.text %>
      </div>
      <% end %>
    </div>


   <!--  <div class="flex-container photos">
      <h2 class="box-title">Photos</h2>
      <div class="restaurant-pictures">
        <% if @restaurant.photos && @restaurant.photos.first && @restaurant.photos[1] && @restaurant.photos[2] %>
        <img src="<%= @restaurant.photos[0] %>" alt="">
        <img src="<%= @restaurant.photos[1] %>" alt="">
        <img src="<%= @restaurant.photos[2] %>" alt="">
        <% end %>
      </div>
    </div> -->
  </div>
</div>